global:
  # How often Prometheus will scrape targets
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-retail-app'
    # By default, Prometheus adds the path /metrics to the target.
    # Spring Boot Actuator uses the path /actuator/prometheus, so we need to overwrite it.
    metrics_path: '/actuator/prometheus'

    # Targets define the services to monitor.
    # Since Prometheus runs in Docker Compose, it can refer to the Spring Boot app by its service name.
    static_configs:
      - targets: ['retail-app:8080']
