spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      fail-fast: false
      properties:
        request.timeout.ms: 3000
        retry.backoff.ms: 1000
        default.api.timeout.ms: 5000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: retail-backend
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.retail_project.*"
        spring.json.add.type.headers: false
    listener:
      auto-startup: ${KAFKA_ENABLED:true}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  cache:
    type: ${SPRING_CACHE_TYPE:redis}

management:
  health:
    redis:
      enabled: false
    kafka:
      enabled: false
